version: "3.7"

services:
  pythonservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: Backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000